### PR TITLE
preventing false positives on words such as 'tester'

### PR DESCRIPTION
**Pull request by rickogden**
Adding a word end \b on the regex seems to prevent certain false positives.

### CODE REVIEW

**Comment by rickogden** [comment]
This caused too many problems, and broke one of the unit tests. The issue is still there though.

**Comment by joshhornby** [comment]
Should fix your issues.

https://github.com/fastwebmedia/Profanity-Filter/commit/422f9bad7ec0f50221316a6192483fb135bc9ce9

Been added to the 1.2 release.

**Comment by rickogden** [comment]
Thanks, also "space" and "spacing" are banned.

**Comment by joshhornby** [comment]
They have been added.

**Comment by rickogden** [comment]
Just to let you know, this only solves the problem if the word is the first word in the checked string: $profanity->check('tester') is fine, but $profanity->check('this is a tester') isn't.

**Pull request closed without merging**
